
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[headers]]
  for = "/*.css"
    [headers.values]
      Content-Type = "text/css"
  for = "/*.js"
    [headers.values]
      Content-Type = "text/javascript"
